// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NearbyShop.Models;

namespace NearbyShop.Migrations
{
    [DbContext(typeof(NearbyShopContext))]
    partial class NearbyShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NearbyShop.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adress");

                    b.Property<string>("description");

                    b.Property<string>("image");

                    b.Property<int>("location");

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("NearbyShop.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ShopId");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("username");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NearbyShop.Models.UserShop", b =>
                {
                    b.Property<Guid>("shopId");

                    b.Property<Guid>("userId");

                    b.HasKey("shopId", "userId");

                    b.HasIndex("userId");

                    b.ToTable("UserShop");
                });

            modelBuilder.Entity("NearbyShop.Models.User", b =>
                {
                    b.HasOne("NearbyShop.Models.Shop")
                        .WithMany("users")
                        .HasForeignKey("ShopId");
                });

            modelBuilder.Entity("NearbyShop.Models.UserShop", b =>
                {
                    b.HasOne("NearbyShop.Models.Shop", "shop")
                        .WithMany()
                        .HasForeignKey("shopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NearbyShop.Models.User", "users")
                        .WithMany("shops")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
